pywr/core.py
tests/test_analytical.py

Here's a quick example of what I mean about comparing the model with some analytical results. It doesn't actual pass a test because the model doesn't handle the nearly zero volume very well. 
I should write the math up in a tex document.

Analytical tests

---

pywr/core.py
pywr/domains/river.py
pywr/solvers/__init__.py
pywr/solvers/cython_glpk.pyx
pywr/solvers/cython_lpsolve.pyx
tests/test_river.py
tests/test_run.py

Hopefully this last commit has fixed the tests with the control curve code.

Fixed control curves.

---

pywr/solvers/cython_glpk.pyx

As discussed it was possible to simplify the LP.

Removed the need for an Output (or Demand) column LP

---

pywr/solvers/cython_glpk.pyx
pywr/solvers/cython_lpsolve.pyx
tests/helpers.py
tests/test_analytical.py
tests/test_run.py

Tests covering some of the issues. All marked as xfail at the moment as we need to decide how to deal with them.

More tests

---

.travis.yml
setup.py
tests/test_core.py
tests/test_run.py
tests/test_scenarios.py

Beginning to address #74.
Need to configure Travis to use `--with-glpk` and `--with-lpsolve`.

Added support to setup.py for --with-glpk and --with-lpsolve

---

README.rst

I would have used a line block, but Github does not display them correctly. I can't be bothered to convert to a README.md

Updated copyright notice

---

pywr/solvers/cython_glpk.pyx
pywr/solvers/cython_lpsolve.pyx

As title: Improved exception when running a model with no valid routes.
Closes #129.

Improved exception when running a model with no valid routes.

---

pywr/_core.pyx
pywr/parameters/_control_curves.pyx
pywr/parameters/_parameters.pxd
pywr/parameters/_parameters.pyx
pywr/parameters/control_curves.py
pywr/recorders.py
tests/test_parameters.py

First item on the list is the biggest. Have added a test for this.
- Updated parent/child approach for Parameter.
- Enabled methods for updating the ControlCurvePiecewiseParameter values for use in optimisation.
- Modified aggregation methodology for AggregatedRecorder and added docstring.

Some updates from using pywr in optimisation.

---

pywr/_core.pyx
pywr/_recorders.pyx
pywr/core.py
pywr/parameters/_parameters.pxd
pywr/parameters/_parameters.pyx
pywr/parameters/control_curves.py
pywr/parameters/parameters.py
tests/test_parameters.py

- Fixes #113 
- Fixes #152
- Cythonised `AnnualHarmonicSeriesParameter`, adds tests and a docstring
- Improves the interface to `ControlCurveParameter` for handling variables.
- Makes `_core.Scenario` init add the itself to the `Model`; previously this was done in the `core.Scenario` subclass.

Some more fixes

---

pywr/parameters/_control_curves.pyx
pywr/parameters/_parameters.pyx
pywr/parameters/control_curves.py
pywr/parameters/parameters.py
tests/models/demand_saving2.json
tests/test_control_curves.py

I've added an example of how to do demand saving using the new IndexedArrayParameter as a test.
This PR closes #143.

Updated docstring and added test for demand saving related parameters

---

pywr/notebook/__init__.py
pywr/notebook/figures.py

This PR adds some standard matplotlib figures for use when calibrating a model.
It includes a limited function for aligning timeseries (`align_series`) which could be improved at some point.

Added some standard figures for calibration

---

pywr/parameters/_parameters.pxd
pywr/parameters/_parameters.pyx
pywr/parameters/parameters.py

As title, this PR moves the aggregated parameters into cython for a modest (by measureable) speedup.

Cythonized AggregatedParameter and AggregatedIndexParameter

---

docs/source/conf.py
docs/source/cookbook/demand_saving.rst
docs/source/index.rst
docs/source/pyplots/demand_saving_levels.py
docs/source/pyplots/top_hat.py

I've already pushed this here: https://pywr.github.io/pywr-docs/cookbook/demand_saving.html
If it's OK I'll merge to master. We could do with another issue that lists other topics that would be helpful. This didn't actually take very long to write.

Added demand saving section to docs

---

pywr/_core.pxd
pywr/_core.pyx
pywr/_recorders.pxd
pywr/_recorders.pyx
pywr/parameters/_parameters.pxd
pywr/parameters/_parameters.pyx
tests/models/demand_saving2.json
tests/models/mean_flow_recorder.json

This can be set directly (node.comment = "hello"), or using
a keyword argument (Node(model, name, comment="hello"), or via
JSON.
Closes #144.

Added comment attribute to Nodes, Parameters and Recorders

---

pywr/parameters/_parameters.pxd
pywr/parameters/_parameters.pyx
tests/test_parameters.py

As discussed earlier, this makes `RecorderThresholdParameter` and `IndexParameter`, and adds "any" and "all" predicates to `AggregatedIndexParameter`.

Enhancements to RecorderThresholdParameter and AggregatedIndexParameter

---

pywr/_core.pxd
pywr/_core.pyx
pywr/core.py
pywr/parameters/_control_curves.pyx
pywr/parameters/_parameters.pxd
pywr/parameters/_parameters.pyx
pywr/parameters/parameters.py
tests/test_control_curves.py
tests/test_parameters.py
tests/test_river.py
tests/test_scenarios.py

- Ditched `ScenarioCombination` class and replaced with a list.
- Improved cython access in `ControlCurveIndexParameter`
- Cythonised `ConstantParameter` and made `IndexedArrayParameter` use this to wrap floats.

Some small performance improvements

---

pywr/_core.pxd
pywr/_core.pyx
pywr/core.py
pywr/solvers/cython_glpk.pyx
pywr/solvers/cython_lpsolve.pyx
tests/test_run.py

Currently enforces the volume constraint in the solver.
Still needs to influence the costs of routes that are connected to it.

Initial work on a VirtualStorage class.

---

pywr/core.py
tests/models/virtual_storage1.json
tests/test_run.py

Added support for virtual storage in JSON

---

pywr/_recorders.pyx
tests/models/parameter_recorder.json
tests/test_recorders.py

Implemented JSON load for ParameterRecorders

---

tests/test_control_curves.py

When `reservoir_with_cc.json` was added a corresponding test wasn't created. This PR does that.
Closes #251.

Added test for reservoir_with_cc.json

---

.travis.yml
appveyor.yml
conda-recipe/meta.yaml
pywr/__init__.py
pywr/core.py
tests/models/aggregated1.json
tests/models/bottleneck.json
tests/models/cost1.json
tests/models/demand_saving.json
tests/models/demand_saving2.json
tests/models/extra1.json
tests/models/mean_flow_recorder.json
tests/models/parameter_recorder.json
tests/models/parameter_reference.json
tests/models/piecewise1.json
tests/models/reservoir1.json
tests/models/reservoir2.json
tests/models/reservoir_with_cc.json
tests/models/river1.json
tests/models/river2.json
tests/models/river_discharge1.json
tests/models/river_discharge2.json
tests/models/river_mrf1.json
tests/models/river_split_with_gauge1.json
tests/models/simple1.json
tests/models/timeseries1.json
tests/models/version1.json
tests/models/virtual_storage1.json
tests/test_core.py

This PR adds a "minimum_version" property to JSON documents. If the version specified is greater than the installed version of Pywr, a warning is raised.

Added minimum_version to JSON document metadata.

---

pywr/parameters/_parameters.pyx
tests/models/multiindex_data.csv
tests/models/multiindex_df.json
tests/models/simple_data.csv
tests/models/simple_df.json
tests/test_parameters.py

Useful for providing constants from a table by looking up column and row.

Added an index argument when loading a DataFrame

---

pywr/domains/river.py
tests/test_river.py

Removed Catchment.check

---

conda-recipe/bld.bat
conda-recipe/build.sh
conda-recipe/meta.yaml
conda-recipe/run_test.bat
conda-recipe/run_test.sh
pywr/notebook/__init__.py
tests/notebook.ipynb

This PR adds a basic test for drawing a network diagram in d3 from Jupyter.
Also fixes a regression introduced in the notebook module (related to `model.node`).
This adds quite a few dependencies to the pywr package - is this something we're OK with? I don't see any need to install jupyter on the cluster...
Build is failing on appveyor for no reason...

Add test for Jupyter notebooks

---

conda-recipe/run_test.bat

Correctly identify Python version in run_test.bat

---

pywr/parameters/_parameters.pyx
tests/test_parameters_cache.py

Fix #286 Caching parameters across scenarios.

---

pywr/core.py
tests/test_control_curves.py
tests/test_core.py
tests/test_license.py
tests/test_run.py

Before model begins current timestep is None. Closes #254.

---

pywr/parameters/parameters.py
pywr/recorders.py
tests/test_recorders.py

Added a optional time Table output to TablesRecorder.

---

pywr/domains/river.py
tests/models/river1.json
tests/models/river2.json
tests/test_river.py

Removed some unused subclasses from domains.river

---

pywr/_core.pxd
pywr/_core.pyx
pywr/parameters/_parameters.pxd
pywr/parameters/_parameters.pyx
pywr/parameters/parameters.py

Doesn't seem to make much of a difference in speed.

Cythonized MonthlyProfileParameter

---

pywr/_core.pyx
tests/test_core.py

```
<Timestep date="2015-12-31">
```
Closes #343.

Added repr to Timestep object

---

pywr/domains/river.py
pywr/parameters/_parameters.pyx
pywr/parameters/control_curves.py
pywr/parameters/parameters.py
pywr/recorders.py
tests/test_parameters.py

Removed useless Parameter class. Fixes #329.

Removed useless Parameter class. Fixes #329.

---

pywr/parameters/_parameters.pyx
tests/test_parameters.py

This adds support for creating `ArrayIndexedScenarioMonthlyFactorsParameter` objects from JSON.
I've used a new syntax here which is different to anything we've done before. Some parameters have an option to load their data from an external file. But this parameter has two (values and factors) that could be external. Can you have a look at how I've handled this and let me know what you think @jetuk?
Closes #339.

Added ArrayIndexedScenarioMonthlyFactorsParameter JSON support

---

pywr/model.py
pywr/recorders.py
tests/models/scenario_monthly_profile.json
tests/models/simple_with_scenario.json
tests/models/timeseries2.json
tests/models/timeseries2_hdf.json
tests/test_recorders.py
tests/test_scenarios.py

Fixes #353 
Following changes
- Ordered JSON format for scenario definition. No change require to `_core.pyx` as it already uses a `list`.
- Improved one of the scenario tests to ensure the multindex returned by `to_dataframe` is correct.
- Changed `TablesRecorder` to save multi dimensional arrays when multiple scenarios are present.
- Added test for this.
- Added scenarios tables to `TablesRecorder` to save the scenario names and sizes.

Fix multiple issues in #353

---

pywr/solvers/cython_glpk.pyx

Updated cross domain terminology in solver

---

pywr/_recorders.pxd
pywr/_recorders.pyx
pywr/parameters/_parameters.pxd
pywr/parameters/_parameters.pyx

in both `AggregatedParameter` and `AggregatedRecorder`
Also added "median" as an option for the `AggregatedRecorder`

Added a property to set the `agg_func`

---

pywr/model.py
pywr/solvers/__init__.py
tests/test_core.py
tests/test_run.py

Added `ModelResult` class, returned by `Model.run()`.
```
res = model.run()
print("{.0f} steps/second".format(res.speed))
```
Closes #386.
Anything further to add?

Added ModelResult class

---

pywr/_recorders.pyx
tests/test_recorders.py

It wasn't properly testing the scenarios. Ooops.

Fixed a mistake in the tests for the FDC deviation recorder 

---

pywr/__init__.py
pywr/model.py
setup.py
tests/test_run.py

```
>>> import pywr
>>> print(pywr.__git_hash__)
c9973a8f25016b8f5b00ec9f46b1283eeef19cbc
```
Closes #389.

Make git hash available as pywr.__git_hash__

---

docs/source/cookbook/dataframes.rst
docs/source/index.rst

This is a work in progress. Creating a PR so I don't forget about it.
Check out the `csv-table` rst directive!

Data frame parameter docs

---

pywr/parameters/_control_curves.pyx

I can't believe how wrong this was!
Closes #336

Corrected ControlCurveInterpolatedParameter docstring. Closes #336.

---

pywr/_core.pxd
pywr/parameters/_parameters.pxd
pywr/parameters/_parameters.pyx
pywr/recorders/__init__.py
pywr/recorders/_recorders.pxd
pywr/recorders/_recorders.pyx
pywr/recorders/calibration.py
pywr/recorders/recorders.py
setup.py
tests/test_recorders.py

I've added a few recorders for computing simple performance/calibration metrics. 
This also refactors `pywr.recorders` to be a subpackage.

Model efficiency recorders

---

pywr/_recorders.pxd
pywr/_recorders.pyx
tests/test_recorders.py

Closes #257.
This will conflict with #397 - I'll sort the merge if you want.

Upgraded MeanParameterRecorder to RollingWindowParameterRecorder

---

pywr/solvers/__init__.py
pywr/solvers/cython_glpk.pyx
pywr/solvers/cython_lpsolve.pyx
pywr/solvers/glpk.pxi
tests/helpers.py
tests/test_run.py

- Added stats dictionary to lpsolve solver
- Added number of rows, columns and nonzeros to GLPK solver
Fixes #351

Added stats to lpsolve and update GLPK stats

---

pywr/_core.pyx

Raise warning for very small factors in AggregatedNode

---

examples/two_reservoir_moea.py

Fix MOEA example.

---

pywr/parameters/_parameters.pyx

Removed superfluous keyword in NegativeParameter

---

pywr/recorders/_recorders.pyx

Also copes with NaN values for aggregation.

Make the FlowDurationCurveDeviationRecorder cope with zero targets

---

pywr/model.py
tests/models/simple_with_scenario.json
tests/test_scenarios.py

Added JSON support for ensemble names in Scenario. 

---

pywr/parameters/_parameters.pyx
tests/test_parameters.py

I had to resort to using numpy for the median function, but I think that's OK.
Also improved the tests for the parameter.
Closes #408.

Added "median" func to AggregatedParameter

---

pywr/parameters/_parameters.pxd
pywr/parameters/_parameters.pyx
pywr/parameters/_thresholds.pxd
pywr/parameters/_thresholds.pyx
pywr/parameters/parameters.py
pywr/recorders/_recorders.pxd
pywr/recorders/_recorders.pyx
pywr/recorders/_thresholds.pxd
pywr/recorders/_thresholds.pyx
pywr/recorders/events.py
pywr/recorders/recorders.py
setup.py
tests/test_parameters.py
tests/test_recorders.py

Created PR for discussion.
Currently does the following,
- Adds EventRecorder and Event object.
- Basic test for capturing the correct events on a scenario basis.
- Creates a pywr.parameters._thresholds module for threshold parameters.
- Moved RecorderThresholdParameter to new module.
- Added NodeThresholdParameter and StorageThresholdParameter.
Todo 
- Track other things during an event.
Also #323 would break some things in here.

WIP: Event recorder

---

pywr/_core.pyx
pywr/model.py
pywr/parameters/_parameters.pxd
pywr/parameters/_parameters.pyx
pywr/recorders/_recorders.pxd
pywr/recorders/_recorders.pyx
tests/models/demand_saving2_with_variables.json
tests/test_core.py
tests/test_parameters.py
tests/test_recorders.py

- Implements is_constraint on Recorder
- Removes API for getting variables from Node or Parameter.
- Adds properties for fetching constraints, objectives and variables from Model.
- Includes a test to load from JSON.
Closes #425
Closes #418

Adds support for constraints, objectives and variable loading from JSON

---

pywr/recorders/events.py
tests/test_recorders.py

There was also a stupid bug with the event duration being negative which was in both the code and tests!

Made the event recorders more robust to aggregation method and no events

---

docs/source/cookbook/aggregated_parameter.rst
docs/source/cookbook/demand_saving.rst
docs/source/index.rst
pywr/parameters/_parameters.pyx
tests/test_parameters.py

This assumes #414 will be merged.
Closes #273.

Added documentation for aggregated parameters

---

pywr/parameters/_parameters.pyx
pywr/recorders/_recorders.pyx
tests/test_recorders.py

Here's a benchmark from ASV
```
before     after       ratio
[919dd7e7] [5e2e9cfc]
-    1.32μs   802.27ns      0.61  benchmarks.AggregatedParameter.time_calc_values(10)
-    8.50μs     1.18μs      0.14  benchmarks.AggregatedParameter.time_calc_values(100)
-   40.52μs     2.68μs      0.07  benchmarks.AggregatedParameter.time_calc_values(500)
```

Vectorised AggregatedParameter.

---

examples/two_reservoir_moea.py
pywr/optimisation/moea.py
pywr/parameters/_parameters.pyx

`InspyredOptimisationModel` doesn't obey the `minimise` / `maximise` flag on `is_objective`. I'll open an issue about that. However the example works again.

Fix moea example

---

pywr/recorders/_recorders.pxd
pywr/recorders/_recorders.pyx
tests/test_recorders.py

The recorder now supports an upper and lower target FDC. Deviation is calculated as positive above
and negative below the respective FDC. If flow is between the two zero deviation is returned.
@Batch21 could give this a read please.

Revised the implemented of the FlowDurationCurveDeviationRecorder

---

pywr/nodes.py
tests/models/breaklink.json
tests/models/transfer.json
tests/test_run.py

This PR adds a compound transfer node, composed of a Storage with zero volume and a Link.
Closes #449.

Added new Transfer node

---

pywr/_core.pyx
pywr/_model.pyx
pywr/notebook/sankey.py
pywr/parameters/_parameters.pxd
pywr/parameters/_parameters.pyx
pywr/recorders/recorders.py
pywr/solvers/__init__.py
pywr/solvers/cython_glpk.pyx
pywr/solvers/cython_lpsolve.pyx
pywr/solvers/glpk.pxi
setup.py
tests/test_recorders.py
tests/test_scenarios.py

- Added routes flows output to `TablesRecorder`
- Added utility function to convert this saved file into d3js format.
- Added `user_combinations` support to `TablesRecorder`
- Requires supporting ScenarioCollection.shape when user_combinations is given.
- Stores data in a flattened formed.
- Adds a table of scenarios combinations stored.

Routes recorder

---

pywr/parameters/_thresholds.pxd
pywr/parameters/_thresholds.pyx
tests/test_parameters.py

The threshold in *ThresholdParameter can now be a Parameter.

---

tests/test_recorders.py

Also the deviation test wasn't really testing anything because it was looking at the input node rather than flow after the abstraction.

Improved the FDC tests by checking my aggregation functions.

---

examples/hydropower_example.json
examples/hydropower_example.py
pywr/_core.pyx
pywr/nodes.py
pywr/parameters/_parameters.pyx
pywr/parameters/parameters.py

If someone has a few minutes it would be good to get an opinion on this new example.
Several requests have come in for hydropower. We should have a good answer to how this is done in pywr.

WIP: Hydropower example

---

pywr/solvers/cython_glpk.pyx

Revert GLPK default log level to "off"

---

pywr/recorders/progress.py
tests/test_recorders.py

Closes #509.
This PR includes a simple text-based progress update, and also a graphical progress bar for Jupyter.

Added ProgressRecorder and JupyterProgressRecorder

---

pywr/solvers/cython_glpk.pyx
pywr/solvers/glpk.pxi

Blacklisted a couple of messages in the term_hook function. This is probably an upstream bug.

Second attempt at fixing #515.

---

pywr/_core.pxd
pywr/_core.pyx
pywr/nodes.py
tests/models/reservoir_evaporation.json
tests/test_run.py

Initial attempt at implementing surface area property for reservoirs (closes #492).
I think this is working, but the "interpolatedlevel" is probably misnamed now.

Initial commit of storage surface area property

---

pywr/_component.pyx
pywr/nodes.py

This PR fixes the things that broke with NetworkX 2.0. Closes #528.

Compatibility with NetworkX 2.x

---

pywr/domains/groundwater.py
pywr/parameters/parameters.py
tests/models/reservoir_evaporation.json

Renamed InterpolatedLevelParameter to InterpolatedParameter

---

pywr/hashes.py
pywr/parameters/_parameters.pyx
tests/models/timeseries2.json
tests/models/timeseries2_hdf_wrong_hash.json
tests/test_hashes.py
tests/test_scenarios.py

- Only supports `DataFrameParameter` and `TablesArrayParameter`.
- Multiple hashes can be given for the same file in JSON.
- Uses hashlib and reads the data in chunks.
Fixes #497

Added optional checksum 

---

pywr/parameters/parameters.py
tests/test_parameters.py

Thanks to @jetuk's abstract class this was easy.

Added InterpolationParameter. Closes #478.

---

pywr/parameters/_parameters.pxd
pywr/parameters/_parameters.pyx
pywr/parameters/parameters.py
tests/test_parameters.py

This PR adds a profile parameter for weekly data (i.e. 52 weeks in a year).

Added WeeklyProfileParameter

---

pywr/parameters/_parameters.pyx

Not sure why this is required, but fixes the problem in #563.

Set freq explicitly in align_and_resample. Closes #563.

---

pywr/_component.pyx
pywr/_model.pyx
pywr/recorders/progress.py

I've started addressing #390. Any comments?

[WIP] Implement logging calls

---

.travis.yml
appveyor.yml
conda-recipe/meta.yaml

lpsolve is available on conda-forge - we should use that instead

Use conda-forge lp_solve

---

pywr/parameters/control_curves.py
pywr/parameters/parameters.py
pywr/recorders/recorders.py
tests/test_control_curves.py

This PR implements the new control curve from #357.
Still needs some documentation.

Added PiecewiseLinearControlCurve

---

pywr/parameters/_control_curves.pxd
pywr/parameters/_control_curves.pyx
pywr/parameters/control_curves.py
tests/test_control_curves.py

Combined commits from #569  and #570.

Combined pyx cc

---

pywr/parameters/_parameters.pyx

The warnings are called when the start and end of the model's timestepping does not align the dataset. In the case of the `DataFrameParameter` this happens before any resampling.
It also adds a `UntilisedDataWanning` to group these warnings together. They can then be easily filtered out.
Fixes #562

Added warnings to DataFrameParamter and TablesArrayParameter

---

pywr/parameters/control_curves.py

This addresses #231. It will be removed in 0.6.

Added DeprecationWarning to AbstractProfileControlCurveParameter

---

CHANGELOG.md

So ... it appears quite a lot of stuff has happened since v0.4 ...

Created a changelog

---

pywr/parameters/parameters.py
tests/pytest.ini

Removes lots of spam when running the tests.

Suppress UnutilisedDataWarning when running the tests.

---

.travis.yml
MANIFEST.in
conda-recipe/bld.bat
conda-recipe/build.sh
conda-recipe/meta.yaml
conda-recipe/run_test.sh
deploy.sh
setup.py

This starts to addresses #613 by fixing `setup.py` and adding a `MANIFEST.in`. I think it works locally for me. If this is OK we can merge and release 0.5.1 to pypi. 
Do you think it possible to do the deploy to pypi with  the `pywr-deploy`? Specifically it would be good to build wheels for all the platforms and upload those.

Fix setup.py and add MANIFEST.in

---

pywr/parameters/_parameters.pxd

I did a search and couldn't see it anywhere else so just deleted the definition (#594)

removed CachedParamter defition

---

pywr/_core.pyx
pywr/_model.pyx
pywr/solvers/__init__.py
pywr/solvers/cython_glpk.pyx
pywr/solvers/cython_lpsolve.pyx
pywr/solvers/glpk.pxi
setup.cfg

This PR adds a configuration for flake8, and fixes some of the warnings it raises.
I'd really like to get to the point where we include flake8 as a hard test. I don't want to cause conflicts with any of the existing PRs though, so it will have to be done later. Let's merge this now and fix as we go along.

Added flake8 config and fix some warnings

---

docs/source/api/pywr.parameters.rst
pywr/parameters/_parameters.pxd
pywr/parameters/_parameters.pyx
pywr/parameters/parameters.py
tests/test_parameters.py

Added ConstantScenarioIndexParameter.

---

pywr/nodes.py
tests/test_run.py

I have added area attribute to Storage() class and added test in test_reservoir_surface_area() using hasattr()

Adding area attribute

---

pywr/parameters/_thresholds.pxd
pywr/parameters/_thresholds.pyx
tests/test_parameters.py

Add ratchet support to threshold parameters.

---

.travis.yml
appveyor.yml
conda-recipe/meta.yaml
pywr/solvers/cython_glpk.pyx
pywr/solvers/cython_lpsolve.pyx

Use this PR/branch to track support for Python 3.7.
- Enable Python 3.7 CI for Linux and Windows. (closes #617)
Build is currently failing.

Python 3.7

---

conda-recipe/run_test.bat
conda-recipe/run_test.sh
pywr/solvers/__init__.py
pywr/solvers/cython_glpk.pyx
pywr/solvers/cython_glpk_edge.pyx
setup.py
tests/test_agg_constraints.py
tests/test_analytical.py
tests/test_recorders.py
tests/test_run.py

Initial commit of an edge based solver using GLPK.

---

docs/source/conf.py
docs/source/cookbook/control_curves.rst
docs/source/cookbook/cookbook.rst
docs/source/cookbook/demand_saving.rst
docs/source/cookbook/extending_pywr.rst
docs/source/extending_pywr/extending_pywr_nodes.rst
docs/source/extending_pywr/extending_pywr_parameters.rst
docs/source/extending_pywr/extending_pywr_recorders.rst
docs/source/extending_pywr/index.rst
docs/source/index.rst
docs/source/license.rst

Work in progress. Creating this PR so that it doesn't get lost. I'm working on writing the "extending pywr" section.

Some documentation

---

pywr/parameters/_parameters.pxd
pywr/parameters/_parameters.pyx
tests/test_aggregated_nodes.py
tests/test_control_curves.py
tests/test_core.py
tests/test_parameters.py
tests/test_recorders.py

Fixed test warnings in aggregate node tests
Will work on other warnings

fixed test warnings

---

pywr/parameters/_parameters.pyx
tests/test_parameters.py

A relatively small change that allows dataframe data to be directly encoded in the JSON document via a "data" key.

Add support for dataframe data embedded directly in to JSON.

---

.travis.yml

Readd missing doctr secured env variable.

---

.travis.yml
travis/manylinux2010_x86_64-glpk/Dockerfile
travis/manylinux2010_x86_64-glpk/Makefile
travis/manylinux2010_x86_64-glpk/build_glpk.sh
travis/manylinux2010_x86_64-glpk/build_lpsolve.sh
travis/manylinux2010_x86_64-glpk/fix-lpsolve-compilation.patch
travis/manylinux2010_x86_64-glpk/lpsolveConfig.cmake.in

The manylinux2010 docker image has just been released. It requires some testing so here is a WIP to test it out here.

WIP: Add Dockerfile and wheel building for manylinux2010.

---

pywr/parameters/_parameters.pyx
pywr/recorders/_recorders.pyx
tests/test_aggregator.py
tests/test_parameters.py
tests/test_recorders.py

Added a `__get__` method for `Recorder.agg_func` and the underlying `Aggregator`.
Closes #681.

Added getter for Recorder.agg_func

---

pywr/recorders/_recorders.pyx
tests/models/agg_recorder_nesting.json
tests/test_recorders.py

- Includes associated test for future regression.

Fix a bug with AggregatedRecorder not returning the instance on load.

---

docs/source/api/pywr.parameters.rst
pywr/parameters/_parameters.pxd
pywr/parameters/_parameters.pyx
tests/test_parameters.py

Add DivisionParameter and tests.

---

pywr/parameters/_parameters.pxd
pywr/parameters/_parameters.pyx
tests/models/flow_parameter.json
tests/test_parameters.py

- Includes a test and test model.

Add flow parameter for tracking yesterday's flow.

---

docs/source/api/pywr.recorders.rst
pywr/recorders/_recorders.pxd
pywr/recorders/_recorders.pyx
tests/test_recorders.py

- NumpyArrayNodeDeficitRecorder - timeseries of deficit.
- NumpyArrayNodeSuppliedRatioRecorder - timeseries of supply / demand
- NumpyArrayNodeCurtailmentRatioRecorder - timeseries of 1 - supply / demand

Add new array deficit recorders.

---

pywr/nodes.py

Remove Blender node.

---

pywr/recorders/recorders.py
tests/test_recorders.py

Fix #766 and tidy-up some old Python 2 stuff.

Fix CSVRecorder volume bug

---

travis/build-wheels.sh

`-eq` is only for integer comparisons.

Fix string equality checking in build-wheels.sh

---

docs/source/cookbook/aggregated_node.rst
docs/source/cookbook/cookbook.rst

Added some docs for AggregatedNode

---

docs/source/install.rst
pywr/_model.pyx
pywr/h5tools.py
pywr/parameters/_parameters.pyx
pywr/parameters/_thresholds.pyx
pywr/parameters/parameters.py
pywr/recorders/_recorders.pyx
pywr/recorders/_thresholds.pyx
pywr/recorders/recorders.py
setup.py
tests/test_analytical.py
tests/test_control_curves.py
tests/test_core.py
tests/test_parameters.py
tests/test_recorders.py
tests/test_river.py
tests/test_run.py
travis/build-wheels.sh

Remove use of past

---

pywr/core.py

Remove warning filters in core.py #797

---

pywr/recorders/_recorders.pxd
pywr/recorders/_recorders.pyx
tests/test_recorders.py

Adding a few additional annual recorders including AnnualTotalFlowRecorder and AnnualCountIndexThresholdRecorder

add additional annual recorders

---

docs/source/api/pywr.parameters.rst
pywr/parameters/_parameters.pxd
pywr/parameters/_parameters.pyx
pywr/parameters/parameters.py
tests/test_parameters.py

daily and weekly scenario profiles

---

.gitignore
pywr/solvers/cython_glpk.pyx
pywr/solvers/cython_glpk_edge.pyx
pywr/solvers/glpk.pxd
pywr/solvers/glpk.pxi
pywr/solvers/glpk.pyx
setup.py

Refactor of common code in the GLPK solvers into a shared parent class.
Closes #760.

Refactor of GLPK solvers

---

pywr/recorders/progress.py

Fix resetting progress of ProgressRecorder.

---

pywr/notebook/__init__.py
tests/models/demand_saving2_with_variables.json
tests/test_notebook.py

Fix for draw_graph bug

---

setup.py

Add .pxd files to package_data in setup.py

---

CHANGELOG.md
docs/source/api/pywr.recorders.rst

Just a couple of the new parameters added to the API docs here and an update to the changelog. All the version numbers should be updated automatically once the merge commit is tagged.

Release v1.5

---

pywr/recorders/_recorders.pxd
pywr/recorders/_recorders.pyx
tests/test_recorders.py

AnnualTotalFlowRecorder can now take a Factor (as a dictionary of (node, factor) pairs. Test added and passing.

AnnualTotalFlowRecorder can now take a Factor. Test Added.

---

pywr/recorders/_recorders.pyx
tests/test_recorders.py

This fixes a bug with the applicatio nof scaling factors when there
are multiple nodes.

Fix the application of scaling factors in AnnualTotalFlowRecorder.

---

README.rst
docs/source/license.rst

Add paper reference to README and documentation.

---

pywr/parameters/_control_curves.pxd
pywr/parameters/_control_curves.pyx
pywr/parameters/control_curves.py
tests/test_control_curves.py

A new parameter the interpolates between multiple control curves in a piecewise fashion. A pair of values is given for each "band" between the storage bounds and the control curves. This pair is used to set linear interpolation based on the current storage.

Add `ControlCurvePiecewiseInterpolatedParameter`

---

pywr/parameters/_parameters.pyx

This parameter `ArrayIndexedScenarioParameter` was not registered.

registering ArrayIndexedScenarioParameter

---

.travis.yml
CHANGELOG.md
docs/source/api/pywr.parameters.rst

@Batch21 would be good to get ~~#857~~ ~~#850~~ ~~#834~~ and maybe ~~#852~~ merged before this release? Is that feasible?
I've also tried to fix #831 in this one.

Release v1.6

---

docs/source/api/pywr.parameters.rst
pywr/parameters/_parameters.pxd
pywr/parameters/_parameters.pyx
tests/test_parameters.py

I also fixed a bug that meant the `NegativeMinParameter` was not being tested and the `NegativeMaxParameter` was not being tested properly.

Add OffsetParameter

---

pywr/optimisation/platypus.py
tests/test_platypus.py

This generator seeds the initial population with a `Solution` that corresponds to the model's current configuration.

Add PywrRandomGenerator as a Platypus generator.

---

docs/source/api/pywr.parameters.rst
pywr/parameters/_parameters.pxd
pywr/parameters/_parameters.pyx
tests/test_parameters.py

See docstring of new parameter for information.

Add RbfProfileParameter.

---

pywr/dataframe_tools.py

Remove unreachable code segment when loading CSV dataframes.

---

docs/source/api/pywr.parameters.rst
pywr/parameters/parameters.py

Add threshold parameters to the API docs.

---

pywr/recorders/_recorders.pyx

Correct MeanParameterRecorder docstring.

---

pywr/nodes.py

Remove incorrect parsing of position keyword in several nodes.

---

setup.py

There was an existing test extra which I renamed to dev.
Fixes #755.

Add optional dependencies for docs and dev.

---

pywr/optimisation/platypus.py
tests/test_platypus.py

This extends the ability of PywrRandomGenerator to return alternative initial solutions instead of just the current model configuration. User's provide a list of dictionaries containing variable values for each of the variable Parameters.
Fixes #887.

Add ability to provide other solutions in PywrRandomGenerator.

---

CHANGELOG.md

Minor release to primarily to address changes to `draw_graph`.

Update changelog ready for v1.7.1 release.

---

CHANGELOG.md

I messed up the sdist for 1.7.1 so it doesn't build properly. Oops!
Release 1.7.2 to fix that.
Another argument for doing this deployment from the CI pipeline instead of relying on me to break things :(

Update changelog ready for v1.7.2 release.

---

docs/source/api/pywr.recorders.rst
pywr/_core.pxd
pywr/_core.pyx
pywr/parameters/_parameters.pxd
pywr/parameters/_parameters.pyx
pywr/recorders/_recorders.pxd
pywr/recorders/_recorders.pyx
tests/test_recorders.py

A new recorder for storing a calculated daily profile. Useful for optimisation where a new profile might be calculated from non-daily profiles and/or combinations of parameters.

Add profile recorder and refactor day of year and week indices.

---

pywr/_core.pxd
pywr/_core.pyx
pywr/nodes.py
pywr/solvers/cython_glpk.pyx
pywr/solvers/cython_lpsolve.pyx
tests/test_agg_constraints.py

@jetuk I think I've got this working for a simple test case for the original glpk solver. As you suggested, I've cached the row and col information for the agg constraints in a simple class, however storing all the column information as a simple list is probably not the most efficient approach. Had a play around with some other approaches using different data types without much success. Any suggestions?

Dynamic factors for Aggregated Node

---

pywr/solvers/__init__.py

This was useful to me the other day for debugging some memory consumption. Probably worth having in the main repo for the future.

Add NullSolver for debugging.

---

docs/source/api/pywr.parameters.rst
pywr/parameters/parameters.py

Add flow param and discount factor param to docs

---

pywr/nodes.py
pywr/notebook/__init__.py
pywr/notebook/save_graph.js

- fix save_graph for models with virtual nodes so that positions are assigned to correct nodes
- add seasonalvirtualstorage to pywr_json_to_d3_json exclusion list
- make component nodes of delaynode children of the main node so that they are not plotted
fixes #937

A few bug fixes for draw and save graph schematic functions:

---

docs/source/api/pywr.parameters.rst
pywr/parameters/_activation_functions.pxd
pywr/parameters/_activation_functions.pyx
pywr/parameters/activation_functions.py
pywr/parameters/parameters.py
setup.py
tests/test_activation_parameters.py

Initial commit of 3 functions - binary step, rectifier and logistic. No tests and only basic docstrings at the moment. Commit mainly for comment.

Several activation functions useful for optimisation.

---

docs/source/api/pywr.parameters.rst
pywr/parameters/_thresholds.pxd
pywr/parameters/_thresholds.pyx
pywr/parameters/parameters.py
tests/test_parameters.py

MultiThresholdIndexParameter to work similarly to a ControlCurveIndexParameter except with Nodes and flows

MultiThresholdIndexParameter

---

pywr/recorders/_recorders.pyx
tests/test_recorders.py

Fix bug loading NumpyArrayNormalisedStorageRecorder from JSON.

---

.github/workflows/build.yml

NetworkX issue here:
https://github.com/networkx/networkx/issues/4732

Pin decorator<5 to satisfy networkx dependency in doc builds.

---

pywr/parameters/_parameters.pxd
pywr/parameters/_parameters.pyx
tests/models/timeseries3_subsample.json
tests/test_parameters.py

Make DF parameter only load required data.

---

pywr/recorders/_recorders.pyx
tests/test_recorders.py

Fix FlowDurationCurveDeviationRecorder load method

---

pywr/parameters/_parameters.pyx

Fixed attribute name in remove method of AggregatedParameter and AggregatedIndexParameter classes

Fixed remove methods in aggregated parameters

---

tests/test_recorders.py

Rename a test that shares the same name as another test.

Fix test name conflict

---

CHANGELOG.md
docs/source/err_perf.rst

- Updated the CHANGELOG with recent changes.
- Corrected new documentation regarding GLPK runtime option.

Release v1.17.0

---

pywr/_core.pxd
pywr/_core.pyx
pywr/nodes.py
tests/test_run.py

Update RollingVirtualStorage to calculate initial utilisation using the initial volume

---

CHANGELOG.md

Bug fix release now #1042 is fixed.

Update changelog for v1.17.2 release

---

pywr/hashes.py
tests/test_hashes.py

update to check hash function to make it not case sensitive. 

---

docs/source/api/pywr.parameters.rst
pywr/parameters/_parameters.pxd
pywr/parameters/_parameters.pyx
pywr/parameters/parameters.py
tests/models/storage_parameter.json
tests/test_parameters.py

Add StorageParameter

---

docs/source/extending_pywr/extending_pywr_parameters.rst

Fix the LicenceParameter example in the docs. Thanks to @ahamilton144 for the contribution.
Fixes #1062.

Fix LicenceParameter example.

---

pywr/parameters/_parameters.pyx
tests/test_parameters.py

fix: Fix bug loading timestep_offset in DataFrameParameter from JSON.

---

pywr/nodes.py
tests/models/loss_link_parameter.json
tests/test_run.py

feat: Support parameter loss_factor in LossLink.

---

pywr/dataframe_tools.py

This allows datasets to be filtered so that only a subset of columns are used in a model.

feat: allow a columns attribute to be sepecified for tables and dataframes
