pywr/pywr

pywr/core.py, tests/test_run.py
Storage should record the current volume, not the change (which is default behaviour for _core.Storage).
=> Removed overloaded after on Storage. 

pywr/core.py, pywr/solvers/__init__.py
This means the imports do not fail when the solver is not built.
Tested on Windows.
=> Added try-except clause around pyd imports. 

pywr/_core.pxd, pywr/_core.pyx, pywr/core.py, pywr/solvers/cython_glpk.pyx, pywr/solvers/cython_lpsolve.pyx, tests/test_analytical.py, tests/test_core.py, tests/test_run.py
More work on cythonizing things. The `Base*`, `StorageInput` and `StorageOutput` are all now in Cython space. It's given a nice speed-up on the London model (~25%)
More can be done if the licence object is cythonized. I guess we could do with some continuous benchmarking.
=> Cythonize storage

pywr/core.py, tests/test_run.py
Required a simple update to a single test. Additionally provides a Timestepper.current property to get the current Timestep object outside of iteration.
=> Refactored Timestepper to store Timestep objects internally for state.

pywr/_core.pyx, pywr/_recorders.pxd, pywr/_recorders.pyx, pywr/recorders.py
Seems an obvious missing recorder. 
Also made the `_recorders` property on `AbstractNode` read-only accessible from Python, and made the `NodeRecorder` object accept `AbstractNode` instead of `Node`.
=> Added NumpyArrayStorageRecorder

pywr/_core.pyx, tests/test_core.py
This PR fixes #82 by initialising _flow in `AbstractNode.__init__`. Otherwise, if `Node.reset` is called before `Model.run`, it attempts to access an uninitialised variable. Added a test that triggers the bug too.
=> Initialise AbstractNode._flow with 0D array in __init__. Fixes #82.

pywr/solvers/__init__.py, pywr/solvers/cython_glpk.pyx
This method uses a dictionary on the solvers to accumulate timings on different parts of the solve. Times are summed with previous totals to accumulate the total time if the solver is used multiple times (i.e. through a series of timesteps).
Opinions please.
=> Initial attempt at adding solver statistics to the GLPK solver.

.travis.yml, setup.py
Some changes to `setup.py`:
- moved to setuptools.setup rather than distutils, and
- display traceback for the solver builds if none of them are successful.
=> Show build errors when no solvers are built

pywr/_core.pyx, pywr/core.py, pywr/solvers/cython_glpk.pyx, pywr/solvers/cython_lpsolve.pyx, tests/fixtures.py, tests/test_core.py
This PR resolves issue #48 (renaming Storage nodes doesn't rename the children) by replacing `Model.nodes` with an instance of `NodeIterator`. The API is unchanged. It also resolves the issue identified in #85, where nodes that raise an exception in their `__init__` were still added to the graph.
=> Refactor of Model.nodes using NodeIterator class

pywr/_core.pyx, pywr/core.py, tests/models/reservoir1.xml, tests/models/reservoir2.xml, tests/test_scenarios.py
This PR resolves #99.
`Storage.volume` now returns an array, instead of just the state of the first scenario. The `Storage.volume` property is now read-only. `Storage.__init__` continues to support `volume` as a keyword argument, but also accepts `initial_volume`.
I've also added a test to check the behaviour of storage volume in under different inflow scenarios. This helped to confirm it was doing the right thing with the numbers.
=> Clarified the purpose of `volume` and `initial_volume` on Storage

pywr/_recorders.pxd, pywr/_recorders.pyx, pywr/core.py, pywr/recorders.py, tests/test_recorders.py
This approach is similar to NodeIterator but is more simple. RecorderIterator is a wrapper around a list of recorders but provides access through keys and also iteration. The used API for Model.recorders is not significantly changed, but now provides access via name.
Recorders have a default name that is the the lowercase of the class name. NodeRecorder and StorageRecorder provide a default naming include the node's name.
=> Add a name to Recorder and use RecorderIterator for access in Model.

pywr/notebook/__init__.py, pywr/notebook/draw_graph.js
This PR adds basic support for displaying a model network in Jupyter using D3 (#125). The usage is simple:
```
from pywr.notebook import draw_graph
draw_graph(model)
```
I think there is a lot of potential using this approach. For example, it should be possible to display model results as attributes on the nodes.
Currently the layout of the graph is force-directed. This could be optional, using the `position` property of the nodes instead.
However I think this is ready to be merged now as it's useful as-is.
=> Display model structure in Jupyter using D3.

pywr/solvers/cython_glpk.pyx, tests/test_run.py
Fixes issue #140.
The problem was when a reservoir has a route that goes from one of it's Inputs to another of it's Outputs.
In the GLPK solver this resulted in the algorithm trying to set the value for the row that constrains changes in the volume of the reservoir twice: +1 for one, -1 for the other.
The fix is to detect this condition and not modify the matrix (i.e. default to 0). I *think* this is the correct thing to do, although if the +1 and -1 didn't cancel out, perhaps due to some loss in the route (which we don't currently implement) this may need more though.
Please you you review this @jetuk. It's the kind of thing that's easy to screw up.
=> Fixed issue with circular route around Storage in GLPK solver.

pywr/notebook/__init__.py, pywr/notebook/draw_graph.js, pywr/notebook/graph.css
This PR uses CSS to style the D3 graph in Jupyter. It has some default styles, but you can provide your own using the `css` keyword argument to `draw_graph`.
Fixes #150 and #151.
=> Color D3 graph using CSS

pywr/_core.pxd, pywr/solvers/cython_glpk.pyx
This PR includes a few speedups in the GLPK solver. Changes include:
- When calculating the cost of a route, all of the node costs are calculated and cached in advance.
- Added a placeholder on `AbstractNode` to store solver-specific data.
- Where feasible moved to `cvarray` instead of `list`.
I suspect additional speedups might be possible if we manage to translate the `routes` list into something more C-ish. However this is not especially easy as it's a list of list of Nodes, with heterogenous length.
This was benchmarked using a model with 143 nodes and 239 routes (the most complex to date!). The changes result in a 2x increase in speed!
=> Speedup for GLPK solver

pywr/core.py, tests/test_core.py
This commit implements the schematic and geographic position attributes discussed in #154.
Note that it's still valid for these properties to be `None` (or `null` in JSON). I don't want to enforce providing them as it's unnecessary for simple models.
=> Added schematic and geographic position attributes to Node

examples/simple_model.py, pywr/core.py
This PR tweaks the keyword arguments to timestepper (and model) to be a little more intuitive. You can now pass a datetime object or a datetime-like string to `Model` and it will do the right thing.
This partly addresses #177 in that it fixes `simple_model.py`. It doesn't run as part of the CI however. This change benefits from the change to timestepper arguments.
=> Timestepper arguments are less fussy about the type passed.

pywr/_recorders.pxd, pywr/_recorders.pyx, pywr/core.py, pywr/parameters/_control_curves.pxd, pywr/parameters/_control_curves.pyx, pywr/parameters/_parameters.pxd, pywr/parameters/_parameters.pyx, pywr/parameters/control_curves.py, pywr/parameters/parameters.py, pywr/recorders.py, tests/test_recorders.py
This commit adds Recorder subclasses for Parameter and IndexParameter. Currently there are NumpyArray... versions of these base classes implemented and tested. Parameters now have access to the _recorders list to find out which Recorder objects are looking at them.
Spotted a couple of bugs on ControlCurveIndexParameter as well that are fixed.
TODO
- Currently there is no way to give a Parameter a name via keyword arguments to __init__.
- More subclasses to use the new Recorders.
=> Add ParameterRecorder and IndexParameterRecorder.

pywr/_recorders.pxd, pywr/_recorders.pyx, pywr/core.py, pywr/parameters/_parameters.pxd, pywr/parameters/_parameters.pyx, pywr/parameters/parameters.py, pywr/recorders.py, tests/models/mean_flow_recorder.json, tests/test_parameters.py, tests/test_recorders.py
This PR adds a `MeanFlowRecorder` which records the mean flow of a node for the past N timesteps, and `RecorderThresholdParameter` which returns one of two values depending on the value of a recorder vs a threshold.
This required a refactor of `load_recorder` to be more in line with `load_parameter`, as recorders can now be a dependency of parameters.
This implements the second point in #155.
=> Added MeanFlowRecorder and RecorderThresholdParameter.

pywr/_core.pxd, pywr/_core.pyx, pywr/parameters/_parameters.pxd, pywr/parameters/_parameters.pyx
This change has a significant impact on the speed of my large (150 node, 250 edges) model. It goes from 1250 timesteps/second to 1900 timesteps/second - a 50% speedup for 3 lines of code!
=> Faster calculation of day of year in _core.Timestep

pywr/_core.pxd, pywr/_core.pyx, pywr/notebook/__init__.py
This PR adds a `virtual` property to all nodes. If the node is virtual it is not rendered in the schematic.
Closes #175.
=> If Node.virtual is True don't draw it in the jupyter schematic.

pywr/parameters/_parameters.pyx
This change catches dataframes that have a string for an index instead of a date object. I'm not sure the message is as helpful as it could be?
Without this you don't know what's wrong until you run the model.
=> Catch invalid dataframe index earlier.

pywr/parameters/_parameters.pyx, tests/test_parameters.py, tests/test_recorders.py
This PR changes the handling of non-leap years by `DailyProfileParameter`. See comments in #212.
The impact on performance is negligible.
=> Fixed handling of non-leap years by DailyProfileParameter. Closes #212.

.coveragerc, README.rst, setup.py
Some support for coverage is better than none, even if it's not working 100% correctly for Cython.
Build cython modules with tracing enabled:
```
python setup.py --with-glpk --with-lpsolve --enable-tracing develop
```
Then run coverage on tests
```
coverage run --source pywr py.test tests
coverage report
coverage html
```
#86
=> Added coverage support

pywr/core.py
This PR addresses #237. Parameters are loaded, even if they aren't referenced anywhere in the JSON.
Also fixes a bug from the switch from recorders being a list to a dictionary.
I need to add a test for this that involves something a little more convoluted: a parameter that references a recorder that references a parameter that references a recorder... or something like that. The fact the current tests pass isn't enough.
=> WIP: Load all parameters

pywr/core.py
This PR makes Timestepper .start, .end and .delta into properties, that can cast inputs automatically. e.g., this is now valid:
```
model.timestepper.start = "1901-01-01"
```
Closes #239.
=> Timestepper.start, .end and .delta are now properties.

pywr/core.py, pywr/parameters/_parameters.pyx, tests/models/parameter_reference.json, tests/test_parameters.py
This PR fixes a bug whereby parameters named in the "parameters" section of a JSON document would be loaded into memory twice. i.e. model.parameters would have multiple entires with the same parameter, but different instances.
Also added a constraint that parameters named in the "parameters" section of the JSON document cannot be literals. This was a required side-effect of the fix.
=> Fixed a bug whereby named parameters were loaded twice in JSON.

pywr/parameters/_parameters.pyx, tests/models/demand_saving2.json, tests/models/extra2.json, tests/test_control_curves.py, tests/test_parameters.py, tests/test_parameters_cache.py
This PR renames the "values" argument to `ConstantParameter` in JSON to "value". This makes more sense to me, given that the value is singular. Previously the name was inherited from `Parameter`.
This will break a lot of existing models, although the fix is trivial. I don't know if we need to start thinking about version numbers...
An altenative approach is to support both forms ("values" AND "value").
=> Renamed ConstantParameter `values` to `value` in JSON

pywr/notebook/__init__.py, pywr/notebook/draw_graph.js
This PR tweaks the graph used in jupyter so that if a node is dragged to a position, it becomes "sticky" (i.e. it will stay where it's dragged to). Double-clicking the node will make the node behave normally again.
=> Position of nodes in d3 graph will be fixed after dragging.

pywr/_recorders.pyx, tests/test_recorders.py
Fixed a bug in MeanFlowRecorder in the conversion of days to timesteps.
Need to add a test for this to prevent regressions.
=> Fixed bug in MeanFlowRecorder related to days->timesteps

pywr/parameters/_control_curves.pyx, pywr/parameters/_parameters.pyx, pywr/parameters/control_curves.py, pywr/parameters/parameters.py, tests/test_parameters.py
This PR changes `parameter_registry` from a set to a dict in order to close #215.
Additionally, a `Parameter.register()` method is added to manage the registry, closing #159.
=> parameter_registry is now a dict

pywr/notebook/draw_graph.js
Added warning for IE about d3 graph arrows. Closes #227.
=> Added warning for IE about d3 graph arrows. Closes #227.

pywr/core.py, pywr/recorders.py, tests/models/demand_saving_with_tables_recorder.json, tests/test_aggregated_nodes.py, tests/test_analytical.py, tests/test_core.py, tests/test_license.py, tests/test_recorders.py, tests/test_run.py, tests/test_scenarios.py
Fixes #268
`TablesRecorder` is now a lot more general.
- It can record multiple `Nodes` and `Parameters`.
- User can specify the path within the h5 file they would like each array saving.
- It can be defined from JSON with filters and mode arguments.
=> Improvements to TablesRecorder

pywr/h5tools.py, pywr/recorders.py, tests/test_recorders.py
This PR moves the code that opens the file recorders write to into the `reset` method.
A new class, `pywr.h5tools.H5Store`, is used to manage the open HDF5 file handle.
=> Moved file-opening into reset method for CSV and H5 recorders.

pywr/_recorders.pyx, tests/test_recorders.py
MeanFlowRecorder and MeanParameterRecorder didn't actually work with scenarios. This wasn't being tested, but is now.
=> Bugfix for mean (flow + parameter) recorders

pywr/recorders.py, tests/test_recorders.py
Closes #278.
Need to document how this works.
If a list of nodes are passed the arrays are named: `/where/node_name`, where where is a constant.
If tuples of (where, node) are used the arrays are named: `/where`
=> Changed syntax for table recorder names

conda-recipe/bld.bat, conda-recipe/run_test.bat
Previously implemented this change for Linux.
=> Clean __pycache__ and related when running conda-build on Windows.

pywr/parameters/_parameters.pxd, pywr/parameters/_parameters.pyx, pywr/parameters/parameters.py, pywr/recorders.py, tests/test_control_curves.py
Two performance improvements related to pytables.
- First is an easy win the `TablesRecorder`
- Second is cythoning the `TablesArrayParameter` this also reads the entire array on init. It's not ideal for indices due to have to type to `double` and cast back to `int`.
=> Performance improvements

pywr/_core.pyx, pywr/core.py, tests/test_core.py
As title. Until we implement the feature we need to warn it's not working.
Related to #242.
=> Raise NotImplementedError if VirtualStoage.cost is non-zero

pywr/parameters/_parameters.pyx, tests/test_parameters.py
This PR adds support for writing a literal into the parameter list for AggregatedParameter. The current requirement is that this is wrapped in a {"type": "constant", "value": X} parameter.
No changes are made to initalisation from Python space. Although it would be possible to do the same thing (convert floats to ConstantParameter), there might be some oddities with the .add/.remove methods, e.g. how should this work:
```
p = AggregatedParameter()
p.add(3.0)
p.remove(3.0)
```
You might expect this to work, but if 3.0 has been converted to a ConstantParameter that is what you'd need to pass to .remove. Also, not just equivalent (e.g. another constant == 3.0) as the set remove function works on the id() of the object, which the user doesn't even have a reference to!
Thoughts @jetuk?
=> Add support for literals in AggregatedParameters. Closes #325.

.travis.yml, appveyor.yml, conda-recipe/meta.yaml, pywr/parameters/_parameters.pyx
Without the change in this commit you get a type error if you try to read an HDF5 table using the TablesArrayParameter with an 8 or 16 bit integer types or 32 bit float type.
I haven't added a test for this yet.
This is required to work with the DSL tables we've recently generated.
=> Added casting in TablesArrayParameter.reset

pywr/solvers/cython_glpk.pyx, pywr/solvers/cython_lpsolve.pyx, tests/test_run.py
Specifically check the model isn't empty when calling the solver's `setup` method and raise an exception if it is.
=> Check model isn't empty in solver setup.

pywr/domains/river.py
RiverSplitWithGauge was incorrectly using `load_parameter` in it's init method. This moves the calls into `load` where they belong.
=> Fixed JSON loading for RiverSplitWithGauge

pywr/model.py, pywr/solvers/cython_glpk.pyx
- `Model.find_all_routes` sorts the nodes by name.
- `setup` in GLPK solver also sorts nodes by name.
This should ensure the rows and columns in the LP are in a deterministic
order.
=> Add deterministic node ordering.

pywr/_recorders.pxd, pywr/_recorders.pyx
A recorder that tracks whether a storage falls below a specified threshold at any point during a model run.
Request also adds  BaseConstantStorageRecorder and MinimumVolumeStorageRecorder to the registry
=> MinimumThresholdVolumeStorageRecorder

pywr/model.py, tests/models/invalid.json, tests/models/invalid_include.json, tests/test_core.py
This PR adds the filename of JSON files to the exception message if an error occurs during parsing. This should help prevent a lot of head scratching!
Example:
```
>>> from pywr.model import Model
>>> model = Model.load("tests/models/invalid_include.json")
Traceback (most recent call last):
File "<stdin>", line 1, in <module>
File "/Users/snorf/Desktop/pywr/pywr/model.py", line 207, in load
return cls.loads(data, model, path, solver)
File "/Users/snorf/Desktop/pywr/pywr/model.py", line 141, in loads
cls._load_includes(data, path)
File "/Users/snorf/Desktop/pywr/pywr/model.py", line 169, in _load_includes
raise(e)
File "/Users/snorf/Desktop/pywr/pywr/model.py", line 164, in _load_includes
include_data = json.loads(f.read())
File "/Users/snorf/miniconda3/envs/pywr/lib/python3.5/json/__init__ …
```
=> Add filename to JSON exceptions for easier debugging

pywr/parameters/_parameters.pxd, pywr/parameters/_parameters.pyx, pywr/parameters/_polynomial.pxd, pywr/parameters/_polynomial.pyx, pywr/parameters/control_curves.py, pywr/parameters/parameters.py, setup.py, tests/test_parameters.py
Two generic polynomial parameters.
The 1D parameter can be related to either a node (for flow), storage (for volume) or another parameter. The 2D parameter is a bit more specialised and uses a storage and parameter for the 2 dimensions. I couldn't think of a clean way to make the choice of the dimensions general while also being efficient.
Fixes #334
=> Add Polynomial parameters

pywr/_recorders.pyx, pywr/recorders.py
This PR changes the way recorders are registered by Pywr to be like Parameters, e.g.:
```
class MyRecorder(Recorder):
....
MyRecorder.register()
```
=> Recorder register syntax is now like Parameters

.travis.yml, appveyor.yml
I think we should continue to support Python 2.7 and Python 3.4 as minimum versions, but have changed the 3.5 tests to 3.6.
=> Upgraded Python 3.5 -> 3.6 in Travis and Appveyor

pywr/_core.pxd, pywr/_core.pyx, pywr/_recorders.pxd, pywr/_recorders.pyx, tests/test_recorders.py
Records number of failures of an `IndexParameter` at or above a threshold.
Also adds convience attributes to `Timestep` for year and day in the same way as month.
=> Add `AnnualCountIndexParameterRecorder`

pywr/_core.pxd, pywr/_core.pyx, pywr/model.py, tests/models/scenario_with_slices.json, tests/models/scenario_with_user_combinations.json, tests/test_scenarios.py
Added support for slicing scenarios, in order to run only a subset.
Example usage:
```
scenario_weather = Scenario(model, size=200)
scenario_demand = Scenario(model, size=3)
scenario_weather.slice = slice(0, 50, 1) # only the first 50 weather scenarios
scenario_demand.slice = slice(2, 3, 1) # only the last demand scenario
```
This partially addresses #385. Not implemented is JSON support (is this needed?) or support for arbitrary combinations.
I'd like to use this next week. We can add the other bits as needed.
=> Added support for slicing scenarios

pywr/model.py
I'm not really sure what's going on here. I was having some problems with a custom variant of ParameterRecorder, where the recorder was failing to load from JSON. I looked at the code to find this section which seems redundant - the recorders are already loaded by this point. Trying to load them again was causing an exception.
=> Removed redundant calls to load_recorders

pywr/h5tools.py, pywr/recorders.py, tests/test_recorders.py
Default is the same as it was, but you can now pass `create_directories=True` and the reorder will make any missing directories for you.
=> Added an option for H5Store and TablesRecorder to create directories

pywr/recorders/_recorders.pyx, tests/test_recorders.py
=> Fix TotalDeficitNodeRecorder to multiply by time-step length.

pywr/recorders/events.py, tests/test_recorders.py
- This sets a minimum duration in time-steps that an event must last to be recorded.
- Also added a test for this.
Fixes #429
=> Added minimum_event_length to EventRecorder

pywr/_core.pxd, pywr/_core.pyx, pywr/parameters/_control_curves.pyx, pywr/parameters/_parameters.pxd, pywr/parameters/_parameters.pyx, pywr/parameters/_polynomial.pyx, pywr/parameters/_thresholds.pyx, pywr/recorders/_recorders.pyx, pywr/recorders/_thresholds.pyx, pywr/solvers/cython_glpk.pyx, pywr/solvers/cython_lpsolve.pyx
- Results from using ScenarioIndex._global_id rather than ScenarioIndex.global_id.
- Also typed the ScenarioCollection so the loop knows .collections is a list.
There is a bunch of time still spent in `calc_values`, but I think most of this is overhead from it being called from Python. I.e. you would need to type the `Parameter` objects in model to make this faster.
=> Performance improvement in calc_values.

pywr/_core.pyx, pywr/model.py, pywr/parameters/_parameters.pyx, tests/test_parameters.py
This commit adds a method helpful in searching for parameters in
the model that aren't used. AbstractNode now provides a components
property which yields all of the components it uses. This is done
using a class attribute, component_attrs, which lists all of the
properties on a class which may hold a component (e.g. max_flow).
This will allow nodes to define new properties in the future,
although most will be caught anyway as all nodes in the model
are queried, including the children of complex nodes.
Also something (I used git stash?) seemed to remove a bunch of blank lines. Hopefully that's not going to create merge issues... I'll sort if it does.
=> Added Model.find_orphaned_components method. Closes #444.

pywr/parameters/_parameters.pxd, pywr/parameters/_parameters.pyx, pywr/parameters/parameters.py
- Sharing the code between AggregatedParameter and AggregatedIndexParameter is nice.
- However it causes unexpected behaviour on AggregatedParameter due it being a subclass of IndexParameter.
=> Removed AggregatedBaseParameter

pywr/solvers/cython_glpk.pyx, pywr/solvers/glpk.pxi
If this occurs a new basis is initialised and solve retried before giving up.
As I mentioned had a weird error with GLPK getting stuck in a seemingly infinite loop. However the dumped LP was easily solved by using `glpsol`from the command line. 
This fix works around this problem by giving a timelimit to GLPK of 5 seconds (not unreasonable to add anyway). If this fails a new basis is created before a resolve. This solves the current problem. If a second failure occurs the solve raises a `RuntimeError` as previously.
@snorfalorpagus comments?
=> Added a timelimit to GLPK simplex method. 

pywr/model.py, pywr/parameters/_control_curves.pyx, pywr/solvers/__init__.py, pywr/solvers/cython_glpk.pyx, pywr/solvers/glpk.pxi, tests/test_run.py
This now does a few things to the GLPK solver
- Added ability to dump MPS file for the last LP.
- Added reset API to solvers
- Tracks the basis (row and column status) for each scenario. This is an attempt to make the solver deterministic when the model is rerun or run with different scenarios. Previously the basis was only crashed once on the first solve and then retained for each solve. Now the basis is crashed on the first time-step of each run for each scenario. The basis is then saved and reapplied on a scenario basis. In theory this makes each scenario entirely deterministic in the behaviour of the basis regardless of whether it is run multiple times or with other scenarios.
- Enabled presolver
Also added a simple NaN check to `ControlCurveInterpolatedParameter`
=> Glpk determinism

pywr/_core.pxd, pywr/_core.pyx, pywr/solvers/cython_glpk.pyx, tests/test_agg_constraints.py
- Implemented in GLPK solver only
- Small refactor of the aggregated nodes in the solver
- Found a small bug in the setting of `None` to min_flow & max_flow on Node
Fixes #461
=> Adds support for Parameter based min & max flow in AggregatedNode

pywr/parameters/_parameters.pyx
Current behaviour means the `TablesArrayParameter` loads data during `reset`. This is inefficient in certain algorithms that reset a model and rerun. The current implementation of the parameter does not expect the data to change between `setup` and `reset`. This moves the loading to `setup` instead.
=> Make TablesArrayParameter load it's data during setup

pywr/parameters/_thresholds.pyx, pywr/recorders/recorders.py, tests/test_parameters.py
Fixes #454.
In the initial timestep the previous flow is undefined. Rather than returning a NaN, the parameter will always return 0 for it's index on the initial timestep.
AssertionRecorder doesn't let you check the index directly, so needed a workaround. See #467.
=> Use node._prev_flow in NodeThresholdParameter. Fixes #454

pywr/recorders/recorders.py, tests/test_recorders.py
Parameters added as children to TablesRecorder.
@jetuk It'd be good to have your eyes on this in case I've missed something.
=> Fixed #465. TablesRecorder sets Parameters as children.

pywr/recorders/recorders.py, tests/test_recorders.py
This avoids a bug whereby resetting the model doesn't remove all the rows
in the time table. Subsequent appends then duplicate the entries. Time
table creation is now done in the reset method.
=> Moved time table creation to reset() in TablesRecorder

pywr/_core.pxd, pywr/_core.pyx, tests/test_core.py
Two features
- Allow some simple aggregated style parameters to be used as max_volume.
- Added feature to set initial storage volume as a proportion of maximum volume. Fixes #453
=> Updates to storage max and initial volume

pywr/_core.pyx
Fixes a bug incorrectly identifying orphaned parameters if a parameter is set to AggregatedNode min_flow or max_flow
=> Added component_attrs to AggregatedNode

pywr/parameters/_parameters.pxd, pywr/parameters/_parameters.pyx, tests/test_scenarios.py
This PR begins to address #489, by only loading data required for the sliced scenario in `TablesArrayParameter`.
TODO:
=> Only load required data in TablesArrayParameter

pywr/_core.pyx, pywr/_model.pyx, pywr/solvers/cython_glpk.pyx
Some changes here:
- Use a fully qualified node name for sorting the nodes & routes in the solver. This should ensure that the order of the columns & rows in the LP is deterministic. Previously this was not the case due to, for example, `Storage` sublinks having the same name.
- Add an absolute epsilon check against (1e-8) before passing row bounds and objective coefficients to GLPK. This was following some advice on the GLPK wiki: https://en.wikibooks.org/wiki/GLPK/Modeling_tips#Close-to-zero_values
- Sorted a `set` that's used for defining the min / max flow constraints on `AggregatedNode`
=> More determinism in GLPK solver

pywr/solvers/__init__.py, pywr/solvers/cython_glpk.pyx, pywr/solvers/glpk.pxi, tests/test_recorders.py, tests/test_run.py
- Added dumping linear programme to GLP file format from GLPK solver.
- Fixes #513 by testing for IPython import.
- Specified minimum_version in some tests to remove warnings.
- Asserted naming warnings are fired by TablesRecorder.
Should be enough for 0.4?
=> Some miscellaneous changes

pywr/nodes.py
Closes #499.
The existing test runs the new code, but doesn't explicitly test it with a non-constant parameter. I think that's OK though, as `load_parameter` is at least being called which should be enough.
=> Load parameters for PiecewiseLink in JSON.

pywr/_model.pyx, tests/test_core.py
This PR allows you to delete compound nodes from a model, including their hidden sub nodes (as suggested in #166).
e.g.
```
del(model.nodes["my reservoir"])
```
It also allows you to delete a node directly rather than by name, e.g. `del(model.nodes[my_reservoir])`. This was required, as the child nodes often don't have unique names (e.g. `[output0]`).
=> Recursive deletion of child nodes when deleting compound nodes.

pywr/_model.pyx
Seems like we had two unfortunate PR at the same time. This fixes the current tests failures on master which occur due to modification of a dictionary during iteration under nx 2.0.
=> Fixed dictionary modification during iteration 

tests/models/.gitattributes
This PR tells Git to always checkout `timeseris2.csv` using unix-style line endings, so the checksum still works on Windows.
=> Added .gitattributes for timeseries2.csv. Closes #536.

pywr/parameters/_parameters.pxd, pywr/parameters/_parameters.pyx
I did this ages ago and forgot about it. It's very useful for variables rather than fiddling with lots of nested `AggregatedParameters` - which aren't supported as `max_volume` on `Storage` because of #470.
=> Added scale and offset to ConstantParameter.

appveyor.yml
conda-forge no longer produces binaries for 3.4 [vc10] which makes testing difficult.
Closes #546.
=> Drop testing of Python 3.4 on Appveyor

pywr/parameters/licenses.py, pywr/parameters/parameters.py, tests/models/annual_license.json, tests/test_license.py
This PR adds support for license parameters (e.g. `pywr.parameters.licenses.AnnualLicense`) from JSON.
=> Added JSON support for license parameters.

pywr/parameters/_parameters.pyx, pywr/recorders/events.py, tests/test_recorders.py
- Adds the ability for Event objects to hold a simple list of values from
a Parameter for the duration of the event.
- Currently only supports Parameters and not other components or nodes.
- New EventStatisticRecorder to compute arbitrary aggregation of the
tracked values and return via .values() and .aggregated_value()
methods.
- Test of the new object and functionality.
There's also another commit tacked on that adds a non-finite value sense check to TablesArrayParameter
=>  Add parameter statistic tracking to EventRecorder

.travis.yml
This PR modifies the `travis.yml` to enable building and testing on OSX. Travis now support OSX builds for open source projects. So this means we can do travis builds for conda. 
Fixes #588 
There's currently an issue with OSX jobs on travis so the builds are being slow. One of these commits has however sucessfully built on the OSX environment, see:
https://travis-ci.org/pywr/pywr/builds/330419345
=> Enabled OSX builds on travis

docs/source/api/pywr.recorders.rst, pywr/recorders/_recorders.pxd, pywr/recorders/_recorders.pyx, tests/models/mean_flow_recorder.json, tests/test_recorders.py
- Current MeanFlowRecorder renamed to RollingMeanFlowNodeRecorder
- It is only a rolling mean recorder, and it is meant for nodes.
- This is a better overall description.
- Added a MeanFlowNodeRecorder that is a simple mean of flow through an
entire model run.
- This doesn't give instantaneous mean flow part way through a run
however.
- Added both to the docs.
=> Improved the mean flow recorders.

pywr/nodes.py, tests/models/reservoir_evaporation_without_area_property.json, tests/test_run.py
While #586 is not ready this takes a couple of commits.
It fixes the issue with area not being loading on `Storage`. However that means the existing reservoir evaporation example doesn't work because of #380. While this is not fixed I've copied the example to make it work if you don't set the `area` property of `Storage` (which isn't required for the evaporation calculation).
Suggest we merge this and do the 0.5 release rather than wait for #586.
=> Make area property load correctly in Storage

conda-recipe/meta.yaml
This reverts commit e6e8fc6ca1d8084eb7d51cf9abed1dc0bc4d0a55.
Fixes #607
=> Revert "Request Cython<0.28 until upstream bug resolved."

conda-recipe/run_test.bat, conda-recipe/run_test.sh, pywr/_model.pyx, tests/conftest.py, tests/fixtures.py, tests/test_agg_constraints.py, tests/test_analytical.py, tests/test_control_curves.py, tests/test_core.py, tests/test_groundwater.py, tests/test_license.py, tests/test_parameters.py, tests/test_piecewise.py, tests/test_recorders.py, tests/test_river.py, tests/test_run.py, tests/test_scenarios.py
- Env variable is used if solver is not given directly.
- If neither given it retains the current default behaviour.
- Removed the "--solver" argument from pytest and the solver fixture.
- Modified all the tests that depended on this fixture.
- Modified the conda recipe to specify solver by environment variable.
Fixes #618.
=> Allow specifying solver name via PYWR_SOLVER environment variable.

.travis.yml, README.rst, appveyor.yml, docs/source/install.rst
Good bye Python 2.7. You have served us well!
Updates README, docs and CI files.
Fixes #572.
=> Drop CI support for Python 2.7 and 3.4.

CHANGELOG.md, pywr/parameters/_parameters.pyx, tests/test_parameters.py
amplitude and phase were not updated correctly. This is pretty subtle, but I think to do with when numpy/cython does or does not make a copy of the underlying memoryview. Anyway I'm pretty sure it wasn't work right, but this makes it much more explicit in any case.
=> Fix a bug in the AnnualHarmonicSeriesParameter 

CHANGELOG.md, docs/source/api/pywr.parameters.rst, docs/source/api/pywr.recorders.rst, pywr/parameters/_hydropower.pxd, pywr/parameters/_hydropower.pyx, pywr/parameters/parameters.py, pywr/recorders/_hydropower.pxd, pywr/recorders/_hydropower.pyx, setup.py, tests/models/hydropower_target_example.json, tests/test_parameters.py, tests/test_recorders.py
This parameter can be used to calculate flow given an energy target. See docstring.
Test included and modifications to existing hydropower recorders docstring to reference this new one. Added a new section to parameters API docs for hydropower.
=> Add new HydroPowerTargetParameter

pywr/optimisation/__init__.py, pywr/optimisation/platypus.py
There are instances where the `cache` variable might not be assigned. Best to remove the finally clause entirely.
=> Removed finally caluse in _cached property of BaseOptimisationWrapper

pywr/parameters/_control_curves.pyx, setup.py
See [here](https://cython.readthedocs.io/en/latest/src/reference/compilation.html#compiler-directives).
Turns on:
- `language_level=3`
- `embedsignature=True`
- `CYTHON_TRACE_NOGIL=1` when profiling is enabled.
I've not turned `binding` on. I'm not sure if it has a performance penalty. 
When experimenting with these there was a test failure in `ControlCurveIndexParameter` that highlighted some dodgy local scoping. I've fixed that too.
=> Additional cython compiler directives.

setup.py
This has become significant as we're publishing to PyPI now, which includes a link to the URL as defined in the setup.py metadata. The current URL doesn't actually resolve. I think it's quite normal to just use the GitHub project for this.
=> Updated url in setup.py metadata to GitHub project

pywr/notebook/__init__.py, pywr/parameters/_parameters.pyx, tests/test_notebook.py
* Skip test_notebook if missing optional dependencies
* Use tkagg backend for matplotlib in tests - I was getting errors otherwise because my default backend (osx) doens't actually work with the way I've installed Python.
* New function `get_parameter_from_registry`.
Closes #624.
I'm wondering if accepting both `"type": "constant"` and `"type": "constantparameter"` is actually a bad code smell and we should require it one way or the other. Perhaps this should be defined as an attribute on `Parameter`, e.g.:
```python
class ConstantParameter(Parameter):
__name__ = "constant"
...
```
That's another issue/PR though.
=> Skip test_notebook if missing optional dependencies

docs/source/api/pywr.recorders.rst, pywr/recorders/_recorders.pxd, pywr/recorders/_recorders.pyx, tests/test_recorders.py
some work on #669 
Currently the area stored by the recorder is calculated using reservoir volume from the previous timestep. I think this is because the `get_area` method of the storage node calls `get_value` on the area parameter which returns the area value calculated in `calc_values`, which is calculated before the reservoir volume is updated for the current timestep.
I’m not sure if this is desirable behavior or not. Changing the `get_area` method so that it calls `value` rather than `get_value` seems to work in terms of recording the area of the current timestep. Should I make this change?
=> Add area recorder

docs/source/install.rst
- Remove pywr conda channel (conda-forge is now used).
- Add section for installing using pip from pypi.
=> Update installation documentation.

pywr/_model.pyx, pywr/recorders/_recorders.pyx
Refactor of the code used to load named parameters and recorders to use shared functions (as they are both components).
Closes #674.
=> Refactor of named parameter/recorder loading

examples/two_reservoir.json, tests/models/two_reservoir.json
The existing code worked because of the costs in the model, but strictly the catchments should use `flow` instead of `max_flow`.
Closes #666.
=> Use flow instead of max_flow in two_reservoirs

pywr/parameters/_control_curves.pxd, pywr/parameters/_control_curves.pyx, tests/models/reservoir_with_cc_param_values.json, tests/test_control_curves.py
This copies the approach of ControlCurveParameter and allows the user
to provide either values as an iterable of floats or parameters as
an iterable of Parameter instances. Each parameter's value is used
during the calculation in the same way as the current list of values.
Tests extended to check this behaviour and support loading from JSON.
=> Allow use of parameters as values in ControlCurveInterpolatedParameter

pywr/domains/river.py, pywr/nodes.py, tests/models/piecewise1_with_parameters.json, tests/test_piecewise.py
The load method on PiecewiseLink was broken when given parameters. It was also a little ambiguous regarding the use of 'max_flow' or 'max_flows', and 'cost' or 'costs'. This is now made explicit to use the singular case. That is consistent with the init methods of the class. Plural keys are no longer supported.
Add a test for loading parameters on to PiecewiseLink sublinks.
Fixes #748
=> Fix loading PiecewiseLink with parameters from JSON.

pywr/__init__.py, pywr/_model.pyx, setup.py, tests/test_run.py
The git hash is part of the version number since we started using
setuptools_scm. This commit removes the generation of a separate
hash file GIT_VERSION.txt as part of setup.py
Fixes #739 and #751
=> Remove GIT_VERSION.txt and pywr.__git_hash__

docs/source/api/pywr.parameters.rst, pywr/parameters/parameters.py, tests/models/simple_with_scenario_wrapper.json, tests/test_scenarios.py
A new parameter for quickly using multiple parameter definitions across
a scenario's ensembles. Useful for cases where non-scenario aware
parameters need to be changed with a scenario's ensemble. For example,
reservoir release rules.
=> Add ScenarioWrapperParameter

pywr/recorders/_recorders.pxd, pywr/recorders/_recorders.pyx, tests/test_aggregator.py
This PR adds support for two additional aggregation functions in the `Aggregator`. These functions are `percentile` and `percentileofscore`; following the names of the underlying numpy/scipy functions. Because these functions require some arguments (unlike the existing min, mean, max, etc) there is a new supported format for specifying agg funcs in the JSON. For example,
```json
{
"func": "percentile",
"args": [95],
"kwargs": {}
}
```
This would allow is to implement more functions in the future.
=> Add support for percentile and percentileofscore aggregation functions.

pywr/_model.pyx, tests/models/my_parameter.py, tests/models/python_include.json, tests/test_core.py
This approach simply detects the file extension of filenames referenced in the existing "includes" section. For .py files runpy is used to execute the code.
Begins to solve #764.
=> Initial implementation of including python modules.

pywr/dataframe_tools.py
This prevents passing a "comment" argument to Pandas when reading from an external source.
=> pop comment from data passed to pandas.read_xxxxx

pywr/parameters/_thresholds.pxd, pywr/parameters/_thresholds.pyx, pywr/recorders/recorders.py, tests/test_parameters.py
These two parameters allow for a comparison against the current year and ordinal day of the simulation respectively. They are useful for triggering things at specific dates in the simulation.
Also 
- adds support for testing index values from the assertion recorder.
- removes an old `basestring` usage in `_thresholds.pyx`
=> Add year and ordinal threshold params

README.rst
The current badge is pointing to the old snorf organisation on Appveyor. This now points to the pywr-admin organisation which is where the builds are done and linked to in the PR.
@snorfalorpagus you might want to disable the Appveyor builds on your account? I think they are being duplicated at the moment.
=> Update Appveyor badge in README.rst

.travis.yml, pywr/parameters/_parameters.pxd, pywr/parameters/_parameters.pyx, pywr/solvers/cython_glpk_edge.pyx, tests/test_parameters.py, travis/build-wheels.sh
This currently supports first and last day of the month interpolation. The interpolation is recalculated in `reset()` so that it will update correctly in the optimisation wrappers. The massaging the profile into a leap year compliant 366 value array is a bit messy :(
Optional features we could add:
- Support middle of the month interpolation.
- Support non-linear interpolation. The code currently uses `np.interp` which only supports piecewise linear, but the scipy interpolation functions could be used instead (as per the existing interpolation parameters).
=> Add daily interpolation support to MonthlyProfileParameter.

appveyor.yml, setup.py
Some refactoring of `setup.py`. It is no longer required to pre-install cython, numpy and packaging - they should be installed automatically.
Closes #809 and #808
=> Refactor of setup.py

docs/source/json.rst, pywr/_model.pyx, tests/test_named_iterator.py, tests/test_node_iterator.py
It's now possible to test for node and component membership using their names:
```python
assert "River Thames" in model.nodes
assert "Demand" in model.parameters
```
If a reference to the actual node is required, using try-except or `.get` is preferable to avoid searching twice.
```python
node = model.nodes.get("River Thames")
if node:
print(f"max_flow: {node.max_flow}")
else:
print("Not found")
```
```python
try:
node = model.nodes["River Thames"]
except KeyError:
print("Not found")
else:
print(f"max_flow: {node.max_flow}")
```
Closes #786.
=> Added __contains__ method to NamedIterator and NodeIterator

tests/test_scenarios.py
Removes a warning:
```
test_scenarios.py::test_scenario_slices
/Users/snorf/Desktop/pywr/tests/test_scenarios.py:318: FutureWarning: .labels was deprecated in version 0.24.0. Use .codes instead.
assert(len(index.labels) == 2)
```
=> .labels is deprecated, use .codes instead

tests/test_core.py
Fixes the following warning(s):
```
test_core.py::test_timeseries_excel[models/timeseries1.csv]
/Users/snorf/Desktop/pywr/tests/test_core.py:205: FutureWarning: Addition/subtraction of integers and integer-arrays to Timestamp is deprecated, will be removed in a future version.  Instead of adding/subtracting `n`, use `n * self.freq`
model.timestepper.end = ts.dataframe.index[-1] - 12
```
=> Fix warning when incrementing timestep by integers

tests/test_core.py
Storage max_volume test function name was repeated. Also tidied up the docstring for the test functions.
=> Fix duplicated test function names.

pywr/notebook/__init__.py
... so that it does not modify a dict when one is passed as an arg.
see #832
=> update to pywr_json_to_d3_json

pywr/parameters/_parameters.pxd, pywr/parameters/_parameters.pyx, tests/models/virtual_storage2.json, tests/test_parameters.py, tests/test_run.py
This commit adds a new parameter that returns a recurring profile that draws down from 1.0 to 0.0 over the course of a year. The day on which to start the drawdown is configurable with the same keywords
as to `AnnualVirtualStorage`.
Basic tests included. Also added a more complex `AnnualVirtualStorage` test model that uses the new `UniformDrawdownProfileParameter` as a control curve in a dynamic cost calculation.
=> Added UniformDrawdownProfileParameter

pywr/_core.pyx, tests/test_aggregated_nodes.py
The previous calculation did not reset the max volume calculation on each loop of the scenarios. Consequently the max volume accumulated with each scenario, and made the current_pc calculation
incorrect. The bug would only impact the first timestep.
=> Fix a bug calculating of AggregatedStorage's initial volume.

pywr/nodes.py
Existing behaviour meant that the keywords `min_flow`, `max_flow` and `cost` were all set to the internal Link. However, these were then overwritten by the call to `super().__init__` and its default values. Now we pass the keywords (in **kwargs) to be set by `super().__init__` rather than directly in local `__init__`.
Fixes #642.
=> Fix the __init__ method of BreakLink.

pywr/parameters/_control_curves.pyx
Removed local type (cdef Storage) in favour of using attribute directly.
=> Fix issue with using AbstractStorage in control curve parameters.

pywr/_core.pxd, pywr/_core.pyx, pywr/nodes.py, tests/test_run.py
This commit adds a new keyword argument to the internal storage reset method. The keyword determines whether initial volume or maximum volume are used to reset the current volume. The default remains to use initial volume. However, the AnnualVirtualStorage node uses the keyword to reset to either value based on its own keyword setting. This gives the user the choice whether the AVS node should reset to initial or maximum volume. Tests included.
Fixes #859.
=> Fix resetting licences to maximum volume by default.

docs/source/api/pywr.recorders.rst, pywr/recorders/_recorders.pyx, tests/test_aggregator.py
This is useful with, for example, the annual count recorders to get a sum of the years with nonzero values (i.e. a count of the number of years with failures).
=> Add count_nonzero aggregation function.

setup.py, tests/test_notebook.py
This should reactivate the `tests/test_notebook.py` module.
=> Add IPython to install dependencies.

pywr/notebook/__init__.py, pywr/notebook/draw_graph.js, pywr/notebook/save_graph.js, pywr/notebook/template.html, setup.py
I’ve moved the notebook `draw_graph` function into a class and added a method to the class that will read the graph and save the positions of any node moved by a user into a new model json file. This hopefully deals with the frustration of spending ages moving nodes around to make a model graph readable only to lose this work when the notebook is reloaded. I’ve also added a method that will save the d3 graph into an html file, which should make it easier to share.
Still needs some work but any initial comments @pywr/pushers ?
=> New notebook graph functionality 

pywr/optimisation/platypus.py, pywr/optimisation/pygmo.py
Log the run time and speed during optimisation, and also save the `ModelResult` on to the wrapper so it can be inspected if required.
=> Expose run statistics to optimisation wrappers

pywr/recorders/_recorders.pxd, pywr/recorders/_recorders.pyx, pywr/recorders/_thresholds.pyx
Update the Cython function signature to `except *` so that exception checking is always done. This is helpful if there are errors during the computation of metrics during optimisation.
=> Change the signature of recorder aggregation functions to catch exceptions.

pywr/notebook/__init__.py, tests/test_notebook.py
This makes it consistent with how the d3 data is created from a model object
=> skip virtual nodes when creating d3 graph data from model json

pywr/notebook/__init__.py
This makes `pywr_json_to_d3_json` and `pywr_model_to_d3_json` consistent in how they deal with virtual nodes.
It also fixes an error that occurred if you tried to add attributes to the graph using `pywr_json_to_d3_json` when the model contained AggregatedNode and/or AggregatedStorage nodes
=> skip AggregatedNode and AggregatedStorage when creating d3 data

pywr/parameters/_parameters.pyx
This allows passing integer values in the JSON.
=> Cast values to np.float64 to ensure correct type.

pywr/notebook/__init__.py, tests/test_notebook.py
Added a check for whether loading from a str and load JSON data
only if a path is given. If given a dict then the JSON data is
the argument.
Fixes #898.
=> Fix PywrSchematic handling of a dictionary of data.

pywr/parameters/_parameters.pxd, pywr/parameters/_parameters.pyx, tests/test_parameters.py
Support optimising the days of year used for interpolation in RbfProfileParameter. Support is provided using a new keyword `variable_days_of_year_range` which defines the maximum deviation from the given days of year that the optimisation use.
In addition new keywords, `min_value` and `max_value`, are added which allowing capping the overall interpolated profile.
=> Add support for optimising the days of year in RbfProfileParameter.

README.rst
The appveyor badge in the README was referring to the latest build rather than the latest master build (i.e. could be a PR). This points the badge at master.
=> Update appveyor badge to refer to master branch

pywr/_core.pxd, pywr/_core.pyx, tests/test_aggregated_nodes.py
This refactors the reset storage code to provide two helper
functions that return the initial volume in absolute and
proprtional terms. These calculations depend on how the initial
and maximum volume is defined.
The AggregatedStorage node uses one these new functions to
correctly calculate its initial volume.
Fixes #918.
=> Fix AggregatedStorage initial volume when defined as proportions.

pywr/solvers/cython_glpk.pyx
Use a small threshold in the difference between upper bounds and lower bounds for a constraint to qualify as GLP_FX. This is a practical consideration where exact floating point equality might not be true in all cases.
May help with #728.
My only comment on this is whether this threshold should be a configurable setting in the GLPK solvers.
=> Add a threshold when checking GLPK constraints bounds equality.

pywr/_component.pxd
This was only needed for Python 2 support.
=> Change basestring to str

docs/source/install.rst
- Use `pytest` instead of the deprecated `py.test`
- Use environmental variable for specifying solver when running tests.
- Fix Appveyor URL.
=> Update install docs

pywr/recorders/_recorders.pyx, tests/test_recorders.py
`AnnualTotalFlowRecorder` and `AnnualCountIndexThresholdRecorder` store their data internally in an annual timeseries. This commit exposes that data as a pandas DataFrame.
=> Add to_dataframe methods to two annual count recorders.

pywr/parameters/parameters.py, tests/test_parameters.py
This could be made a bit cleaner by changing the api and requiring the `kind` kwarg to be included with `interp_kwargs` rather than allowing it to still be defined separately. What do you think @jetuk 
See also #889
=> update load methods of interpolation parameters so that they accept interp1d kwargs

pywr/recorders/_recorders.pxd, pywr/recorders/_recorders.pyx, tests/test_recorders.py
This new option means the counts are ignored for the excluded months if they are defined. This allows counting only a sub-set of months during a year.
=> Add optional exclude_months to AnnualCountIndexThreshRecorder

README.rst
These links must have changed when we moved the documentation build system.
=> Fixed documentation links in README

.github/workflows/build.yml, README.rst, docs/source/install.rst, setup.py
Pandas 1.2 has been released and no longer supports reading xlsx files with `xlrd`. Openpyxl is the preferred default.
=> Switch to openpyxl instead of xlrd and drop Python 3.6 support.

pywr/_core.pxd, pywr/_core.pyx
Add methods to core nodes to get values for all scenarios. This is more efficient than call the `get_xxx` methods many times.
=> Add `get_all_xxx` methods to core nodes.

.github/workflows/build.yml
This adds CI builds for Python-3.9 on manylinux. Windows is blocked by missing PyTables wheels.
=> Add Python-3.9 manylinux builds to CI.

pywr/_component.pxd, pywr/_component.pyx, tests/test_parameters.py
Parameters and Recorders can now optionally take a dict of tags. The component just stores these in a public attribute. It will
be useful for various tools to provide and save metadata about components. E.g. for filtering and grouping.
This PR doesn't use this metadata anywhere. It should be possible to add tags to the `TablesRecorder` parameter arrays as metadata.
=> Add an optional tags dictionary to Component

pywr/recorders/kde.py, pywr/recorders/recorders.py, tests/test_recorders.py
Added an implementation of a recorder that uses a KDE to estimate storage probabilities. It uses a reflected KDE to estimate the bounded distribution of proportional storage. It returns a PDF and provides a probability of being at or below a target storage via the `.aggregated_value()` method.
=> Add GaussianKDEStorageRecorder.

pywr/recorders/_recorders.pxd, pywr/recorders/_recorders.pyx, pywr/recorders/kde.py, tests/test_recorders.py
Works in a similar way to `GaussianKDEStorageRecorder`, but derives from a new array recorder. `NormalisedGaussianKDEStorageRecorder` keeps an array of storage that is normalised between -1 and 1 where the 0 value is at a control curve. The new KDE recorder estimates a probability of being at or below zero in the normalised series.
=> Add NormalisedGaussianKDEStorageRecorder

pywr/_core.pxd, pywr/_core.pyx, pywr/parameters/_activation_functions.pyx, pywr/parameters/_parameters.pxd, pywr/parameters/_parameters.pyx, pywr/solvers/cython_glpk.pyx
This builds upon #912 by applying similar logic but to parameters whose values do not change with time or scenario. A new attribute `is_constant` is added to the `Parameter` class which indicates if this is true. If it is true then new methods provide access to the constant value without need for a timestep or scenario index. 
New attributes and methods on the `Node` class then allow the solver to determine if flows are fixed (doubles) or constant (doubles or parameters with `is_constant`). The solver then sets the constant values during reset instead of setup. This means that constant parameters can be used for optimisation and still have their updated values applied to a new model run (i.e. one that does reset and not setup).
It passes all the tests, but I haven't done a wider test or a …
=> Update constant Parameters in reset rather than every timestep.

.github/workflows/run-tests.sh, pywr/_core.pxd, pywr/_core.pyx, pywr/solvers/__init__.py, pywr/solvers/cython_glpk.pyx
This is a performance improvement that follows on from #983
by only updating aggregated node factors in the GLPK solvers
during reset instead of every timestep. It should have most
benefit for models which use many of aggregated nodes with factors
as the code both for calculating the normalised factors is
not very efficient.
A new solver option and corresponding environment variable is
added to turn this feature on. It is off by default.
Modified the CI test suite to run only with and without the
extra options. As opposed to running each option individually.
=> Update constant aggregated node factors only during rest.

.github/workflows/build.yml
neworkx have released a fix for the original issue - https://github.com/networkx/networkx/pull/4815
=> unpin decorator dependency in doc build as networkx now requires >5

pywr/recorders/_recorders.pyx, tests/test_recorders.py
`NumpyArrayNodeSuppliedRatioRecorder` and `NumpyArrayNodeCurtailmentRatioRecorder`
could both error with a divide by zero if the max flow of the parameter
they monitor returned zero.
Fixes #991
=> Fix divide by zero error in two recorders.

pywr/_core.pxd, pywr/_core.pyx, pywr/recorders/_recorders.pyx, tests/test_core.py, tests/test_recorders.py
These methods can be used by annual recorder to make sure that the correct proportion of flow is allocated to correct year when the timestep delta is greater than 1 day
=> Add methods to Timestep to return days in current and next year

.github/workflows/build.yml
Publishing only happens on tagged commits. If this works as
expected we can follow-up with another commit to move to
live PyPI.
Beginning of the end for #944
=> Add CI steps to publish wheels and sdist to test PyPI.

pywr/solvers/cython_glpk.pyx, tests/models/virtual_storage3.json, tests/models/virtual_storage4.json, tests/test_control_curves.py, tests/test_core.py, tests/test_run.py
In response to #1001 this commit implements a check to the `glp_set_mat_row` call to ensure that there is at least one entry in the row. Zero entry rows are likely caused by invalid or unsupported model / network configuration (e.g. those reported in #1001). For the time being this change will ensure such models fail to run with an `AssertionError` instead of failing to apply expected constraints silently.
I suggest we merge this rapidly and release a bug fix ASAP.
A proper fix to enable support for a `PiecewiseLink` or other complex nodes with `VirtualStorage` is still required.
=> Assert entries when creating rows in the GLPK matrix.

.github/workflows/build.yml
The current approach failed because the pypi-publish action does not run on Windows. The recommended approach is to use a separate job that downloads the final artifacts (wheels and sdist) before uploading to PyPI.
=> Update the PyPI publishing in GA pipeline.

docs/source/cookbook/aggregated_parameter.rst
Docs incorrectly include a "threshold" for a `NegativeParameter` and misses some commas in the JSON definitions.
=> Fix doc error about aggregated parameters

pywr/recorders/calibration.py
Circular import causes a problem with some tools (e.g. mypy). It is unnecessary in this case by importing directly from the Cython module.
=> Remove circular import in calibration recorders module.

README.rst
Point new users to PyPi instead of compiling Pywr from source.
=> Update README install instructions

pywr/nodes.py
It was using `self.name` before it was initialised resulting in all internal nodes being called `None <something>`. Use the name argument directly instead.
=> Fix internal node names for PiecewiseLink.

.github/workflows/build.yml
Python 3.7 is a bit old and not all packages will support it in future.
=> Use Python 3.9 for building the documentation

.github/workflows/run-tests.sh, docs/source/err_perf.rst, docs/source/index.rst, pywr/solvers/__init__.py, pywr/solvers/cython_glpk.pyx, pywr/solvers/libglpk.pxd, setup.py, tests/models/aggregated_with_two_nodes_same_route.json, tests/test_agg_constraints.py, tests/test_run.py
This picks up some work from #759 and the work done in #762 to
improve the error handling in GLPK. Best to read the new page
in the documentation that's been added about this. The TLDR
is that this adds NaN checks and GLPK error handling to Pywr
by default at the cost of some performance. The older
behaviour can be created with `--glpk-unsafe` compile time flag.
There are two new tests that cause seg faults with the unsafe
interface (i.e. current behaviour). Raising exceptions is better
from a handling point of view for users wrapping models in
multi-processing, etc.
Queries:
- Should the unsafe interface be a runtime option instead of
a compile time option?
- Is changing the default error handling behaviour a good idea?
Useful reference: https://en.wikibooks.org/wiki/GLPK/Error_handling
=> Improve GLPK error handling.

pywr/_core.pxd, pywr/_core.pyx, pywr/parameters/_control_curves.pyx, pywr/parameters/_polynomial.pyx
The current approach requires Parameter writers to handle
NaN values for current_pc. NaNs can occur when storage nodes
have zero maximum volume. This PR adds a convenience method
to get a finite and bounded current_pc for all storage nodes.
Pywr's internal parameters are updated to use this in preference
to direct access of the ._current_pc memory view.
Parameter writers should also use this new cpdef function instead
of using .current_pc directly.
There are two recorders which still use the raw ._current_pc
memory view for their data outputs. Those could be updated too.
We should also add some explicit tests for cases where using this
new internal function makes a difference.
=> Improve handling of NaN current pc in storage nodes.

pywr/solvers/cython_glpk.pyx, pywr/solvers/cython_lpsolve.pyx, tests/helpers.py, tests/models/simple1_broken.json, tests/models/simple1_semi_broken.json, tests/test_run.py
If the user doesn't run `Model.check()` then the error from the solver is quite cryptic if their are missing connections between nodes. This change raises a `ModelStructureError` with a message containing the relevant node name which should help debugging some common mistakes.
=> Improve solver error messages for invalid networks.

.github/workflows/build.yml
This might not work just yet due to our dependencies, but we can re-run the pipeline until it does.
=> Build & test Python 3.10 wheels.

CHANGELOG.md
This release is just to release the new wheels for new Python versions.
=> Update changelog for 1.17.1 release

pywr/_core.pyx
This changes fixes a bug where there Parameters attached to an AggregatedNode are incorrectly identified as being orphaned.
=> Add factors to AggregatedNode component_attrs

pywr/_model.pyx
For a complex model I'm running this change dramatically reduces the overhead time of running the model from ~370 seconds to ~45 seconds.
It looks like a lot of the time is caused buy a few piecewise links that are very central to the network and therefore have a lot of routes associated with them. However, when using the `glpk-edge` solver only routes of 2 nodes to be assessed to get the cross-domain links. Limiting the length of routes that `all_simple_paths` searches for makes it this much faster.
=> Pass cutoff arg to call to nx.all_simple_paths

pywr/_model.pyx, tests/test_core.py
This fixes a bug with how keyword arguments are passed between the various load methods. The bug meant that any solver passed to .load() was ignored. This fixes that and adds tests. The keyword argument overrides both the solver settings in the JSON data and PYWR_SOLVER environment variable.
Fixes #1042
=> Correct the use of keyword arguments in Model.load

docs/source/cookbook/aggregated_node.rst
Updates the cookbook comment that implies factors must be
constants. This is no longer the case.
=> Remove outdated comment on constant factors in AggregatedNode.

pywr/recorders/_recorders.pxd, pywr/recorders/_recorders.pyx, tests/test_recorders.py
Updates to the recorder add four new arguments to specify start and end dates in a year where an Annual count is to be recorded.
=> Update to AnnualCountIndexThresholdRecorder to include a range of days to record

.github/workflows/build.yml, pyproject.toml, setup.py
Add a new optional dependency group for notebook sub-package. This
removes ipython, matplotlob and jinja2 from core dependencies.
=> Move project dependencies to pyproject.toml

pywr/_core.pyx, tests/test_core.py
This removes the requirement that both initial volume and initial volume pc need to given by a user when a storage max volume attribute is set as a constant parameter. For non-constant parameters both still need to be given.
=> Allow storage max volume to be set as a constant parameter without specifying both initial volume and initial volume pc.

pywr/domains/river.py, pywr/nodes.py, pywr/notebook/__init__.py, pywr/notebook/sankey.py, pywr/optimisation/pygmo.py, pywr/parameters/_parameters.pxd, pywr/parameters/_parameters.pyx, pywr/profiler.py, pywr/recorders/recorders.py, tests/test_activation_parameters.py, tests/test_agg_constraints.py, tests/test_df_resampling.py, tests/test_multi_models.py, tests/test_parameters.py, tests/test_recorders.py, tests/test_run.py, tests/test_scenarios.py
This adds a new feature to allow offsetting the timeseries provided by DataFrameParameter and TablesArrayParameter. This would allow the user to look-up future or past values if required.
Some minor black formatting updates too.
=> feat: Add timestep offset to DataFrameParameter and TablesArrayParameter

docs/source/api/pywr.parameters.rst, pywr/parameters/_parameters.pxd, pywr/parameters/_parameters.pyx, pywr/parameters/parameters.py, pywr/recorders/_recorders.pyx, pywr/recorders/recorders.py, tests/models/mean_flow_parameter.json, tests/test_parameters.py
Add a new parameter that computes the rolling mean flow of the previous N timesteps. This is the parameter equivalent of `RollingMeanFlowNodeRecorder`. This recorder has been marked as deprecated. Users should prefer this new parameter to the older recorder.
=> feat: Add RollingMeanFlowNodeParameter

CHANGELOG.md
Couple of queries ahead of this release:
- Should we do a README update (see #1070) first?
- Should we also convert `RollingWindowParameterRecorder` to a parameter as per #1074 ?
=> Update changelog for v1.20.0 release.

pywr/nodes.py, tests/test_recorders.py
This fix allows PiecewiseLink to return the sum of its sublinks min and max flows. While the solver won't use these methods because the outer node is not added to the LP it does allow recorders to get the total min and max flows for the entire node.
Test implemented for deficit recorder.
Fixes #1087.
=> fix: Overload get_xxx_flow for PiecewiseLink.

pywr/recorders/recorders.py, tests/test_recorders.py
Add metadata to the CArray nodes created in the HDF5 file by TablesRecorder. Metadata saves the type of attribute and the class name of the source of the data.
=> feat: Add metadata to TablesRecorder arrays.

pyproject.toml, setup.py
Cython v3 was released a couple of days ago. There are some build and runtime issues caused by the update. These will need resolving. In the meanwhile pin to the older version so we can keep releasing.
=> chore: Pin Cython<3 until support is resolved.

pyproject.toml, pywr/parameters/_parameters.pyx, pywr/parameters/_polynomial.pyx, pywr/solvers/cython_glpk.pyx, setup.py
Several updates required to handle building with Cython 3.x.
- Include `noexcept` for GLPK callback functions.
- Handle name mangling of attributes using __. Cython 3 aligns more closely with Python 3 in this respect.
There should be a review of the use of `except` given the new behaviour in Cython 3, but that is not done here.
=> chore: Support Cython 3.x

pywr/parameters/_parameters.pyx, tests/models/loss_link_table.csv, tests/models/loss_link_table.json, tests/test_run.py
Try to load parameter as values (i.e. from a table or values entry) if there is no "type" entry. This should allow more flexible definitions of models where tabular data can be used where a parameter is required. Previously only a literal constant or Parameter definition were allowed.
=> feat: Fallback to loading from values or tables.

pywr/parameters/_thresholds.pyx, tests/test_parameters.py
This allows parameters that do not define a value method (e.g. `AggregatedParameter`) to be used as thresholds
=> fix: use `get_value`` method when fetching threshold param value within threshold parameters

.github/workflows/build.yml, docs/source/install.rst, pyproject.toml, setup.py
Modernisation of the build process and project metadata.
- Move more metadata to pyproject.toml (from setup.py).
- Specify the build-system and backend.
- Remove parsing command line arguments in build (this is not supported). Allow existing CLI arguments to be passed as environmental variables instead.
- Update CI accordingly.
- Update installation instructions.
=> chore: pyproject.toml and build modernisation.

.github/workflows/build.yml
There's an inconsistency in GLPK version between the Linux and Windows wheels. This update ensures they are both using v5. It requires updating to the latest manylinux image and fetching the Windows GLPK binaries from Conda Forge.
=> Glpk v5 wheels
